### ISSUE TITLE
this gem should be renamed

### ISSUE THREAD

**Issue by igalic** [voxpupuli/voxpupuli-release-gem#1]
pinging @rnelson0, as chief naming officer

**Comment by rnelson0** [comment]
voxpupuli-release is my preference!
>
>

-- 

Rob Nelson
rnelson0@gmail.com

**Comment by igalic** [comment]
do it so, number one.

**Comment by rnelson0** [comment]
Number 1 doesn't have the power of greyskull. Yet.

**Comment by igalic** [comment]
apparently, our default team permissions for new repositories are `read`
